# Generated by Django 6.0 on 2026-01-09 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('editora', models.CharField(max_length=200)),
                ('pagina', models.IntegerField(default=0)),
                ('isbn', models.IntegerField(default=0)),
                ('sinopse', models.TextField(max_length=400)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.autor')),
            ],
        ),
    ]
