# Generated by Django 6.0 on 2026-01-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='escolha',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='question_text',
            new_name='questão',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='votos',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='questão',
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Data da publicação'),
        ),
    ]
