# Generated by Django 6.0 on 2026-01-08 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choice_text_choice_escolha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='questão',
            new_name='questao',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questão',
            new_name='questao',
        ),
    ]
